import{a as b,S as E,i as d}from"./assets/vendor-BDaiwwc1.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))A(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&A(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function A(e){if(e.ep)return;e.ep=!0;const i=s(e);fetch(e.href,i)}})();const g="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEoSURBVHgBrZXtEYIwDIZDT86/biKjuBFlEt0AV3EX/tB61Abo8dUkRXjvqj2bvk8KSQUgZK0tjbEuZWAs5XOhzJ0DnWXw7rruA6zU3X9ovwfyPK9AUsi8bc0LEoWx0kn+Nk+GHDEXIWeYkxDOvGmaQjKMxSwg46ReBxljCunFheTiEFvjGgzZtzpm4IM0BZlObom9rRYBFEQynwMuIOh6zbU3wmnfTChsQj8qXJP2i4A1ZAQkmaMUJEopcLG5pKQThLsJMx9/Sr57RMDcPDyW+TsRIVwVcdXClfCwvihTutH4UhwgsUbD5u0BIciY7zMGAUGxGPRaJMdB9mpjHnQGhDQ/AyKaH4Fw5ps+CNdClrnSf98A+D99pdTdOffYc330mk4iD+6x/ACnmEjn99LB/AAAAABJRU5ErkJggg==",m="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAE7SURBVHgB3VVtccMwDFUYhMHMYIUQCIUQBguDhEnCYBuClkHHIGHQMtCk6/Pi8/lz25/23b3L1ZLfkxtZIXp0NLkEZm7l0QtfhQbLN+Gn8Nw0zUa/gQgb4cw7NuEZvDrrM4rw9x9S4h1ElJOaRQpYYGy82AjzQ0j8iOAlJJyDIz5RpKoVbP9VHAkzEgxVokTc2JdGlciKI6n3q092Qo04Et+1a1xxbBz/LI7kk/a4tzbFTGLi8vtNOBQZxExSlcd0NKCXZqXw6X5Mcn8L3y/nRygwYONLxiQlbjuxDwXb1GbHZEjEZ78T/YQFRzRUCS65R0hSA51DxaMCp19Bk0vuUEk+eS/qgj1HKgHfJ+pqj8zxcT3yPtY7qgHv897iih4/OebRAixKPplGHp1Qj2/fyyb8Ei7yybzRU+Mbv95G35qxX4AAAAAASUVORK5CYII=",x="47379272-a961c7172d29abe92af06f616",c=new URLSearchParams({key:x,q:"yellow+flower",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:15}),U="https://pixabay.com/api/";async function p(t=U,a={params:c}){const{data:s}=await b(t,a);return s}function u(t){return t.map(({id:a,webformatURL:s,tags:A,likes:e,views:i,comments:l,downloads:y,largeImageURL:w})=>`
        <li data-id="${a}" class="list__item">
          <a class="gallery-link" href="${w}">                          
            <img class="item-img" src="${s}" alt="${A}"/>                  
          </a>
          <ul class="item-container-list">
              <li class="container-list">
                <h3 class="item-title">Likes</h3>
                <p class="item-content">${e}</p>
              </li>
              <li class="container-list">
                <h3 class="item-title">Views</h3>
                <p class="item-content">${i}</p>
              </li>
              <li class="container-list">
                <h3 class="item-title">Comments</h3>
                <p class="item-content">${l}</p>
              </li>
              <li class="container-list">
                <h3 class="item-title">Downloads</h3>
                <p class="item-content">${y}</p>
              </li>
            </ul>          
        </li>
    `).join("")}const f=new E(".list a",{captionsData:"alt",captionDelay:250}),R=document.querySelector(".form"),h=document.querySelector(".list"),r=document.querySelector(".js-load-more"),o=document.querySelector(".js-loader");R.addEventListener("submit",S);r.addEventListener("click",B);let n=1;c.set("page",n);const L=c.get("per_page");function S(t){t.preventDefault();const a=t.target.elements.message.value.trim();a&&(o.classList.remove("hidden"),c.set("q",a),n=1,c.set("page",n),p().then(s=>{if(r.classList.add("hidden"),o.classList.remove("hidden"),!s.total){d.show({theme:"dark",iconUrl:g,backgroundColor:"#EF4040",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageLineHeight:"150%",position:"topRight",maxWidth:"354px"}),h.innerHTML="",r.classList.add("hidden"),o.classList.add("hidden");return}h.innerHTML=u(s.hits),o.classList.add("hidden"),s.totalHits>n*L?r.classList.remove("hidden"):d.show({theme:"dark",iconUrl:m,backgroundColor:"#59a10d",message:"We're sorry, but you've reached the end of search results.",messageSize:"16px",messageLineHeight:"150%",position:"topRight"}),f.refresh()}).catch(s=>{d.show({theme:"dark",iconUrl:g,backgroundColor:"#EF4040",message:`Error: ${s.message}`,messageSize:"16px",messageLineHeight:"150%",position:"topRight",maxWidth:"354px"}),h.innerHTML="",r.classList.add("hidden"),o.classList.add("hidden")}).finally(()=>{t.target.reset()}))}async function B(){o.classList.remove("hidden"),r.classList.add("hidden"),n++,c.set("page",n);try{const t=await p();h.insertAdjacentHTML("beforeend",u(t.hits)),o.classList.add("hidden"),t.totalHits>n*L?r.classList.remove("hidden"):d.show({theme:"dark",iconUrl:m,backgroundColor:"#59a10d",message:"We're sorry, but you've reached the end of search results.",messageSize:"16px",messageLineHeight:"150%",position:"topRight"});const s=document.querySelector(".list__item").getBoundingClientRect().height;window.scrollBy({left:0,top:s*2.3,behavior:"smooth"}),f.refresh()}catch(t){d.show({theme:"dark",iconUrl:g,backgroundColor:"#EF4040",message:`Error: ${t.message}`,messageSize:"16px",messageLineHeight:"150%",position:"topRight",maxWidth:"354px"})}}
//# sourceMappingURL=index.js.map
